/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoogleOauthRouteImport } from './routes/google-oauth'
import { Route as IndexRouteImport } from './routes/index'

const GoogleOauthRoute = GoogleOauthRouteImport.update({
  id: '/google-oauth',
  path: '/google-oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/google-oauth': typeof GoogleOauthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/google-oauth': typeof GoogleOauthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/google-oauth': typeof GoogleOauthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/google-oauth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/google-oauth'
  id: '__root__' | '/' | '/google-oauth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoogleOauthRoute: typeof GoogleOauthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/google-oauth': {
      id: '/google-oauth'
      path: '/google-oauth'
      fullPath: '/google-oauth'
      preLoaderRoute: typeof GoogleOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoogleOauthRoute: GoogleOauthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
